# This is the corrected blueprint for deploying a pre-built Rasa Docker image.

services:
  # --- The main Rasa Server ---
  - name: rasa-server
    type: web
    env: image      # Corrected from 'docker' to 'image'
    plan: free
    healthCheckPath: /
    # The image to pull from Docker Hub
    image:
      url: rasa/rasa:latest-full
    # The command to run after pulling the image
    startCommand: rasa run -m models --enable-api --cors "*" --port 8080

  # --- The Rasa Action Server ---
  - name: action-server
    type: web
    env: image      # Corrected from 'docker' to 'image'
    plan: free
    # The image to pull from Docker Hub
    image:
      url: rasa/rasa-sdk:latest
    # The command to run after pulling the image
    startCommand: rasa run actions --port 8080