services:
  # --- The main Rasa Server (Corrected) ---
  - name: rasa-server
    type: web
    env: docker  # Use 'docker' to build from a Dockerfile
    plan: free
    healthCheckPath: /
    # Tell Render where to find your Dockerfile
    dockerfilePath: ./Dockerfile
    # You no longer need the 'image' or 'startCommand' sections here,
    # as they are defined in the Dockerfile.

  # --- The Rasa Action Server (still has the same issue) ---
  - name: action-server
    type: web
    env: image
    plan: free
    image:
      url: rasa/rasa-sdk:latest
    startCommand: rasa run actions --port 8080