# This blueprint tells Render how to deploy your Rasa chatbot.
# It creates two services: one for the main Rasa server and one for the action server.

services:
  # --- The main Rasa Server ---
  # This is the service that users will talk to.
  - name: rasa-server
    type: web
    env: docker
    plan: free # Use the free instance type
    healthCheckPath: /
    envVars:
      - key: RASA_MODEL_SERVER_URL
        fromService:
          name: rasa-server
          type: web
          envVarKey: RASA_MODEL_SERVER_URL
    dockerCommand: rasa run -m models --enable-api --cors "*" --port 8080
    # You may want to use a specific version of Rasa here
    dockerImage: rasa/rasa:latest-full

  # --- The Rasa Action Server ---
  # This service runs your custom Python code from the /actions folder.
  - name: action-server
    type: web
    env: docker
    plan: free # Use the free instance type
    # Make sure your actions code is in the /actions directory
    dockerCommand: rasa run actions --port 8080
    dockerImage: rasa/rasa-sdk:latest