services:
  # --- The main Rasa Server ---
  - name: rasa-server
    type: web
    env: docker
    plan: free
    # Tell Render where to find your first Dockerfile
    dockerfilePath: ./rasa-server.Dockerfile

  # --- The Rasa Action Server (Corrected) ---
  - name: action-server
    type: web
    env: docker          # Corrected from 'image'
    plan: free
    # Tell Render where to find your second Dockerfile
    dockerfilePath: ./action-server.Dockerfile